setwd("/Users/Aoji.Xie/Desktop/LDSC_analysis/common_snp")

library(data.table)

all_snp <- data.frame(fread("/Users/Aoji.Xie/Desktop/DNA_Methylation/test_M/combat_controled_by_model/ldsc/w_hm3.snplist"))
dim(all_snp)
head(all_snp)
all_LD <- data.frame(fread("/Users/Aoji.Xie/Desktop/LDSC/all_LD_score"))
dim(all_LD)
head(all_LD)
all_LD$BP <- as.numeric(all_LD$BP)



## import the cytosine information (generated by linear model with butyrate in PD)
meth_data <- data.frame(fread("/Users/Aoji.Xie/Desktop/DNA_methylation_analysis/butyric/methylation_results_PD_butyric.txt"))
head(meth_data)
dim(meth_data)




meth_data <- meth_data[,c("Row.names", "P.Value", "t", "B", "CHR", "MAPINFO")]
meth_data$low <- meth_data$MAPINFO - 10000
meth_data$high <- meth_data$MAPINFO + 10000


### extract all SNPs within +- 10000 bp range of each cytosine
split_table = function(table){
  l <- list()
  for (i in 1:22){
    
    l[[i]] <-  subset(table,table$CHR == i)
  }
  return(l)
}

snp_lst <- split_table(all_LD)
prob_lst <- split_table(meth_data)



for(m in 1:1){
  v1 <- snp_lst[[m]]
  v1$SNP <- as.character(v1$SNP)
  v1 <- na.omit(v1)
  v2 <- prob_lst[[m]]
  v2$distance <- 10000 
  v2$SNP <- "no"
  for(i in 1:nrow(v1)){
    for (j in 1:nrow(v2)){
      if(v1$BP[i] < v2$high[j] & v1$BP[i] > v2$low[j]){
        
        distance <- abs(v2$MAPINFO[j]- v1$BP[i])
        
        if(distance < v2$distance[j]){
          v2$distance[j] <- distance
          v2$SNP[j] <- as.character(v1$SNP[i])
        }
        
      }
    }
    print(i)
    print(m)
  }
  name <- paste("chr" , m , sep = "_")
  write.table(v2, name, row.names = FALSE, sep = "\t", quote = FALSE)
  
}